In [1]:
import numpy as np
import os
from mlp import MLP

# XOR

In [2]:
X = np.array(
    [
        [0, 0], 
        [0, 1], 
        [1, 0], 
        [1, 1]
    ])

y = np.array([
        [0], # 0 xor 0 = 0
        [1], # 0 xor 1 = 1
        [1], # 1 xor 0 = 1
        [0]  # 1 xor 1 = 0
    ])

In [3]:
print(f"Dimensões de X_train: {X.shape}")
print(f"Dimensões de y_train: {y.shape}")
mlp = MLP(n_inputs=X.shape[1], n_hidden=X.shape[1], n_output=1)
mlp.treino(X, y, epochs=10000, eta=0.1)

Dimensões de X_train: (4, 2)
Dimensões de y_train: (4, 1)


In [4]:
for _ in range(len(X)):
    print(f'Input: {X[_]} | Output: {int(mlp.predict(X[_]) > 0.5)} | Expected: {y[_]}')

Input: [0 0] | Output: 0 | Expected: [0]
Input: [0 1] | Output: 1 | Expected: [1]
Input: [1 0] | Output: 0 | Expected: [1]
Input: [1 1] | Output: 1 | Expected: [0]


/tmp/ipykernel_159926/383637444.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print(f'Input: {X[_]} | Output: {int(mlp.predict(X[_]) > 0.5)} | Expected: {y[_]}')


### Teste com mais de 2 entradas

In [5]:
from helper.load_data import load_data
import os
data_dir = os.path.join(os.getcwd(), '..', 'data', 'XOR')

for file in os.listdir(data_dir):
    print(f"Arquivo: {file}")
    file_path = os.path.join(data_dir, file)
    X, y = load_data(file_path=file_path)

    mlp = MLP(n_inputs=X.shape[1], n_hidden=X.shape[1], n_output=1)
    mlp.treino(X, y, epochs=10000, eta=0.1)

    print(f'Input: {X[_]} | Output: {int(mlp.predict(X[_]) > 0.5)} | Expected: {y[_]}')

Arquivo: n6.txt


/tmp/ipykernel_159926/2169098450.py:13: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print(f'Input: {X[_]} | Output: {int(mlp.predict(X[_]) > 0.5)} | Expected: {y[_]}')


Input: [0 0 0 0 1 1] | Output: 1 | Expected: [1]
Arquivo: n7.txt
Input: [0 0 0 0 0 1 1] | Output: 1 | Expected: [1]
Arquivo: n9.txt
Input: [0 0 0 0 0 0 0 1 1] | Output: 1 | Expected: [1]
Arquivo: n5.txt
Input: [0 0 0 1 1] | Output: 1 | Expected: [1]
Arquivo: n8.txt
Input: [0 0 0 0 0 0 1 1] | Output: 1 | Expected: [1]
Arquivo: n3.txt
Input: [0 1 1] | Output: 1 | Expected: [1]
Arquivo: n4.txt
Input: [0 0 1 1] | Output: 1 | Expected: [1]


# O problema do Autoencoder

In [6]:
caso_encoder = [
    {'N': 8, 'epochs': 10000},
    {'N': 15, 'epochs': 15000},
]

In [7]:
for caso in caso_encoder:
    N = caso['N']
    epochs = caso['epochs']
    
    # Identidade NxN
    X = np.identity(N)
    y = X.copy()

    # Camada escondida Log2(N)
    hidden_size = int(np.log2(N))
    
    # Teinar a rede para o encoder de tamanho N
    mlp = MLP(n_inputs=N, n_hidden=hidden_size, n_output=N)
    mlp.treino(y=X, X=y, epochs=epochs, eta=0.1)
    
    # 'Predict' desta merda
    predictions = mlp.predict(X)
    print(f"Predict: Encoder de tamanho N={N}:\n", np.round(predictions, decimals=2))


Predict: Encoder de tamanho N=8:
 [[0.89 0.   0.   0.03 0.03 0.06 0.   0.  ]
 [0.   0.89 0.   0.   0.08 0.07 0.04 0.  ]
 [0.   0.02 0.93 0.05 0.   0.06 0.04 0.  ]
 [0.07 0.   0.04 0.93 0.   0.01 0.   0.03]
 [0.08 0.06 0.   0.   0.91 0.   0.01 0.01]
 [0.05 0.07 0.01 0.01 0.   0.9  0.   0.  ]
 [0.   0.06 0.07 0.   0.01 0.   0.91 0.06]
 [0.01 0.   0.   0.05 0.03 0.   0.05 0.94]]
Predict: Encoder de tamanho N=15:
 [[0.84 0.1  0.04 0.04 0.   0.   0.   0.   0.   0.   0.   0.12 0.03 0.
  0.  ]
 [0.12 0.76 0.02 0.22 0.   0.   0.   0.   0.   0.17 0.   0.   0.08 0.
  0.  ]
 [0.   0.   0.38 0.06 0.   0.   0.   0.16 0.01 0.   0.   0.   0.11 0.
  0.16]
 [0.   0.1  0.05 0.24 0.   0.   0.   0.   0.   0.05 0.   0.   0.1  0.
  0.  ]
 [0.   0.   0.   0.07 0.79 0.   0.03 0.   0.19 0.19 0.   0.   0.   0.01
  0.  ]
 [0.   0.   0.01 0.   0.   0.8  0.09 0.08 0.   0.   0.01 0.05 0.   0.
  0.  ]
 [0.   0.   0.   0.   0.   0.11 0.85 0.   0.09 0.   0.02 0.   0.   0.
  0.  ]
 [0.   0.   0.28 0.01 0.   0.16 0.   0